#!/usr/bin/python

import httplib, urllib, sys, json

# Define the parameters for the POST request and encode them in
# a URL-safe format.

from sys import argv

script, filename, tofile = argv

txt = open(filename)
file_contents = txt.read()

params = urllib.urlencode([
    ('js_code', file_contents),
    ('compilation_level', 'WHITESPACE_ONLY'),
    ('output_format', 'json'),
    ('output_info', 'compiled_code'),
])

# Always use the following value for the Content-type header.
headers = { "Content-type": "application/x-www-form-urlencoded" }
conn = httplib.HTTPConnection('closure-compiler.appspot.com')
conn.request('POST', '/compile', params, headers)
response = conn.getresponse()
data = response.read()
js = json.loads(data)

if js['compiledCode']:
    target = open(tofile, 'w')
    target.write( js['compiledCode'] )
else:
    params = urllib.urlencode([
        ('js_code', file_contents),
        ('compilation_level', 'WHITESPACE_ONLY'),
        ('output_format', 'text'),
        ('output_info', 'errors'),
    ])
    conn.request('POST', '/compile', params, headers)
    response = conn.getresponse()
    data = response.read()
    print data

conn.close